### ISSUE TITLE
Can not create keyDir: /data/coding-ide-home/workspace/ruifzw/ssh-key

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE-Workspace#2]
net.coding.ide.model.exception.WorkspaceCreationException: Can not create keyDir: /data/coding-ide-home/workspace/ruifzw/ssh-key
       	at net.coding.ide.model.Workspace.<init>(Workspace.java:81)
       	at net.coding.ide.service.WorkspaceManagerImpl.getWorkspace(WorkspaceManagerImpl.java:310)
       	at net.coding.ide.service.WorkspaceManagerImpl.createNewWatcher(WorkspaceManagerImpl.java:376)
       	at net.coding.ide.service.WorkspaceManagerImpl.watch(WorkspaceManagerImpl.java:356)
       	at net.coding.ide.service.WorkspaceManagerImpl.onApplicationEvent(WorkspaceManagerImpl.java:336)
       	at net.coding.ide.service.WorkspaceManagerImpl.onApplicationEvent(WorkspaceManagerImpl.java:62)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:497)
       	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
       	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
       	at com.sun.proxy.$Proxy126.onApplicationEvent(Unknown Source)
       	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
       	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
       	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
       	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
       	at net.coding.ide.web.message.EventExchange.onSessionConnected(EventExchange.java:81)
       	at net.coding.ide.web.message.EventExchange.onApplicationEvent(EventExchange.java:57)
       	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
       	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
       	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
       	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
       	at org.springframework.web.socket.messaging.StompSubProtocolHandler.publishEvent(StompSubProtocolHandler.java:365)
       	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageFromClient(StompSubProtocolHandler.java:284)
       	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:307)
       	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
       	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
       	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
       	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
       	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:409)
       	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:194)
       	at org.springframework.web.socket.sockjs.transport.handler.SockJsWebSocketHandler.handleTextMessage(SockJsWebSocketHandler.java:92)
       	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
       	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:110)
       	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42)
       	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81)
       	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:78)
       	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
       	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:106)
       	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
       	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
       	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
       	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69)
       	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
       	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
       	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
       	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
       	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
       	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: /data
       	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
       	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
       	at java.nio.file.Files.createDirectory(Files.java:674)
       	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
       	at java.nio.file.Files.createDirectories(Files.java:767)
       	at net.coding.ide.model.Workspace.<init>(Workspace.java:79)
       	... 53 common frames omitted

**Comment by tanhe123** [comment]
https://github.com/Coding/WebIDE-Backend/pull/1

**Comment by tanhe123** [comment]
Coding/WebIDE-Backend#1

**Comment by Honghe** [comment]
目前需要先手动创建 `/data` 目录，同时设置为对应账户拥有读写权限

**Comment by tanhe123** [comment]
@Honghe 已修改逻辑，默认为用户目录下的 `.workspace`，参见 Coding/WebIDE-Backend#1
